use st;

ALTER TABLE fact_sjukfall ADD INDEX IDX_FACT_SJUKFALL_GENDER (gender);
ALTER TABLE fact_sjukfall ADD INDEX IDX_FACT_SJUKFALL_LAN (lan);
ALTER TABLE fact_sjukfall ADD INDEX IDX_FACT_SJUKFALL_ENHET (lakare);
ALTER TABLE fact_sjukfall ADD INDEX IDX_FACT_SJUKFALL_KAPITEL (dxkapitel);